[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
shared = { workspace = true }

tokio = { workspace = true }
axum = { workspace = true }
futures-util = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
webrtc = { workspace = true }
bytes = { workspace = true }
async-trait = { workspace = true }
